#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v3
# autospec commit: c1050fe
#
# Source0 file verified with key 0xB92A5F04EC949121 (sitter@kde.org)
#
Name     : phonon-vlc
Version  : 0.11.3
Release  : 7
URL      : https://download.kde.org/stable/phonon/phonon-backend-vlc/0.11.3/phonon-backend-vlc-0.11.3.tar.xz
Source0  : https://download.kde.org/stable/phonon/phonon-backend-vlc/0.11.3/phonon-backend-vlc-0.11.3.tar.xz
Source1  : https://download.kde.org/stable/phonon/phonon-backend-vlc/0.11.3/phonon-backend-vlc-0.11.3.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause LGPL-2.1
Requires: phonon-vlc-data = %{version}-%{release}
Requires: phonon-vlc-lib = %{version}-%{release}
Requires: phonon-vlc-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : phonon-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(libvlc)
BuildRequires : vlc-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package data
Summary: data components for the phonon-vlc package.
Group: Data

%description data
data components for the phonon-vlc package.


%package lib
Summary: lib components for the phonon-vlc package.
Group: Libraries
Requires: phonon-vlc-data = %{version}-%{release}
Requires: phonon-vlc-license = %{version}-%{release}

%description lib
lib components for the phonon-vlc package.


%package license
Summary: license components for the phonon-vlc package.
Group: Default

%description license
license components for the phonon-vlc package.


%prep
%setup -q -n phonon-backend-vlc-0.11.3
cd %{_builddir}/phonon-backend-vlc-0.11.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1702048341
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%cmake .. -DPHONON_BUILD_PHONON4QT5=ON
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1702048341
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/phonon-vlc
cp %{_builddir}/phonon-backend-vlc-%{version}/COPYING.LIB %{buildroot}/usr/share/package-licenses/phonon-vlc/9a26d3fdb6503d43ee9d39d82b61b6a99a862400 || :
cp %{_builddir}/phonon-backend-vlc-%{version}/cmake/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/phonon-vlc/ff3ed70db4739b3c6747c7f624fe2bad70802987 || :
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/locale/ca/LC_MESSAGES/phonon_vlc_qt.qm
/usr/share/locale/ca@valencia/LC_MESSAGES/phonon_vlc_qt.qm
/usr/share/locale/cs/LC_MESSAGES/phonon_vlc_qt.qm
/usr/share/locale/da/LC_MESSAGES/phonon_vlc_qt.qm
/usr/share/locale/de/LC_MESSAGES/phonon_vlc_qt.qm
/usr/share/locale/en_GB/LC_MESSAGES/phonon_vlc_qt.qm
/usr/share/locale/es/LC_MESSAGES/phonon_vlc_qt.qm
/usr/share/locale/et/LC_MESSAGES/phonon_vlc_qt.qm
/usr/share/locale/eu/LC_MESSAGES/phonon_vlc_qt.qm
/usr/share/locale/fi/LC_MESSAGES/phonon_vlc_qt.qm
/usr/share/locale/fr/LC_MESSAGES/phonon_vlc_qt.qm
/usr/share/locale/gl/LC_MESSAGES/phonon_vlc_qt.qm
/usr/share/locale/hu/LC_MESSAGES/phonon_vlc_qt.qm
/usr/share/locale/id/LC_MESSAGES/phonon_vlc_qt.qm
/usr/share/locale/it/LC_MESSAGES/phonon_vlc_qt.qm
/usr/share/locale/ko/LC_MESSAGES/phonon_vlc_qt.qm
/usr/share/locale/nl/LC_MESSAGES/phonon_vlc_qt.qm
/usr/share/locale/nn/LC_MESSAGES/phonon_vlc_qt.qm
/usr/share/locale/pl/LC_MESSAGES/phonon_vlc_qt.qm
/usr/share/locale/pt/LC_MESSAGES/phonon_vlc_qt.qm
/usr/share/locale/pt_BR/LC_MESSAGES/phonon_vlc_qt.qm
/usr/share/locale/ro/LC_MESSAGES/phonon_vlc_qt.qm
/usr/share/locale/ru/LC_MESSAGES/phonon_vlc_qt.qm
/usr/share/locale/sk/LC_MESSAGES/phonon_vlc_qt.qm
/usr/share/locale/sl/LC_MESSAGES/phonon_vlc_qt.qm
/usr/share/locale/sv/LC_MESSAGES/phonon_vlc_qt.qm
/usr/share/locale/uk/LC_MESSAGES/phonon_vlc_qt.qm
/usr/share/locale/zh_CN/LC_MESSAGES/phonon_vlc_qt.qm
/usr/share/locale/zh_TW/LC_MESSAGES/phonon_vlc_qt.qm

%files lib
%defattr(-,root,root,-)
/usr/lib64/qt5/plugins/phonon4qt5_backend/phonon_vlc.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/phonon-vlc/9a26d3fdb6503d43ee9d39d82b61b6a99a862400
/usr/share/package-licenses/phonon-vlc/ff3ed70db4739b3c6747c7f624fe2bad70802987
